# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments
gems: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Quaro
description: Quaro competition
url: "https://mengxinji.github.io/Quaro"
baseurl: "/Quaro"
#logo: halve.png                                       # Site logo
locale: en_US
github:
  url:               "https://mengxinji.github.io/Quaro/"
author:
  name:              "Mengxin"
  email:             "mengxin.ji1992@gmail.com"
  twitter:          # "paululele"
  instagram:        # "paululele"
  github:            "MengxinJi"
  facebook:          "Mengxin Ji"
  linkedin:          "Mengxin Ji"

# google_analytics: UA-52446115-1
repo: http://github.com/nandomoreirame/end2end
disqus_shortname: "nandothemes"
disqus_site_shortname: "nandothemes"

# Author settings
author:
  name      : Mengxin Ji
  job       : Ph.D. student
  #bio       : "Enthusiast performance, responsive design and usability,
  #always looking for the best project and good coffee."
  thumb     : /images/author.jpg
  email     : "mji@gmail.com"
  url       : https://mengxinji.github.io/MengxinJi.github.io/
  github    : http://github.com/mengxinji
  twitter   : http://twitter.com/mengxinji
  facebook  : http://facebook.com/mumujimx
  linkedin  : http://linkedin.com/in/mengxinji

# navbar pages
navbar:
  - slug: about
    title: About
  # - slug: resume
  #   title: Resume
  # - slug: skills
  #   title: Skills
  - slug: blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
