# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments
gems: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Quaro
description: "Quaro Competition"
keywords: "kaggle, LSTM, WordToVec, Quaro"
url: https://mengxinji.github.io/Quaro
baseurl: "/Quaro"
# baseurl: ""

# google_analytics: UA-52446115-1
repo: https://github.com/MengxinJi/Quaro
disqus_shortname: "MengxinJi"
disqus_site_shortname: "MengxinJi"

# Author settings
author:
  name      : Mengxin Ji
  job       : PhD student
 # bio       : "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
  thumb     : /images/author.jpg
  email     : mji@ucdavis.edu
  url       : http://
  github    : http://github.com/MengxinJi
  twitter   : http://twitter.com/mengxinji
  facebook  : http://facebook.com/mumujimx
  linkedin  : http://linkedin.com/in/mengxinji

# navbar pages
navbar:
  - slug: about
    title: About
  # - slug: resume
  #   title: Resume
  # - slug: skills
  #   title: Skills
  - slug: blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
