# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:title/
#relative_permalinks: true

# Setup
title:            Quaro Competition
tagline:          'A project webpage'
description:      'Quora competition'
url:              "https://mengxinji.github.io/Quaro/"   
baseurl:          "/Quaro" 


author:
  name:           'Mengxin Ji'
  url:            "https://twitter.com/mengxinji"

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:          "https://github.com/MengxinJi/Quaro"
